name: pg_dorm
description: Dart simple orm for postgress
version: 0.0.1+3
repository: https://github.com/gumi-apps/pg_dorm

environment:
  sdk: ^3.3.3
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build: ^2.4.1
  dart_style: ^2.3.6
  json_annotation: ^4.8.1
  postgres: ^3.1.2

  analyzer: ^6.8.0
  source_gen: ^1.5.0
  yaml: ^3.1.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  
