name: project_mega
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build:
  d_orm:
    path: /home/nurad/d-orm
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.13.0
  dart_style: ^2.3.6
  json_annotation: ^4.8.1
  postgres: ^3.1.2

dev_dependencies:
  build_runner:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  source_gen:
  test: ^1.19.2
  very_good_analysis: ^5.1.0
# dependency_overrides:
#   meta: ^1.12.0
